<ChatsCard>:
    style: "elevated"
    orientation: 'vertical'
    padding: [10, 10, 10, 10]
    spacing: 10
    adaptive_height: True
    theme_bg_color: 'Custom'
    md_bg_color: app.theme_cls.surfaceContainerHighColor

    MDLabel:
        text: root.chatusername
        font_style: "Title"
        role: 'medium'
        adaptive_height: True

    MDWidget:
        size_hint: 1, None
        height: "75sp"